export default {
  onBoardingPic: require('../assets/images/onboardingImage.png'),
  onBoardingPic2: require('../assets/images/onboardingImage2.png'),
  ic_back: require('../assets/images/ic_back.png'),
  logo: require('../assets/images/Logo/Logo.png'),
  sampleImage: require('../assets/images/sampleImage.png'),
  instuctorSample: require('../assets/images/instuctorSample.png'),
  resumeSample: require('../assets/images/sampleResume.png'),
  studySample: require('../assets/images/studySample.jpg'),
  logoBig: require('../assets/images/Logo/logoBig.png'),
  Student: require('../assets/images/Student.png'),
  Teacher: require('../assets/images/Teacher.png'),
  businessPhoto: require('../assets/images/businessPhoto.png'),
  cabin: require('../assets/images/cabin.png'),
  mathBlue: require('../assets/images/FormulablueBack.png'),
  sampleThumbanail: require('../assets/images/sampleThumbnail.png'),
  wishlistIcon: require('../assets/images/wishlistIcon.png'),
  sampleEditImage: require('../assets/images/sampleEditImage.png'),
  editBlueIcon: require('../assets/images/editBlueIcon.png'),
  sampleTestImage: require('../assets/images/sampleImageMy.png'),
  themeTicket: require('../assets/images/blueTicket.png'),
  goldenTicket:require('../assets/images/goldenTicket.png'),
  profileDp: require('../assets/images/profileDp.png'),
  splashGif : require('../assets/images/BrightFutureSplash.gif'),
  splashNewGif : require('../assets/images/Brightfutureanimation.gif'),
  splashNewGifFast : require('../assets/images/brightFutureAnimationFast.gif'),
  splashNewGifTab : require('../assets/images/tabSplash.gif'),
  CongratsGif : require('../assets/images/Congrats.gif'),
  verify : require('../assets/images/verified.png'),
  joinButton : require('../assets/images/JoinGroup.png'),
  whiteBtn:require("../assets/images/Icons/whiteBtn.png"),
  eyeIcon :require("../assets/images/eyeOutline.png"),
  notesIcon :require("../assets/images/notesIcon.png"),
  playIcon :require("../assets/images/PlayLight.png"),
  greyIcon :require("../assets/images/greyIcon.png"),
  blueIcon :require("../assets/images/blueIcon.png"),
  notesLight :require("../assets/images/notesLight.png"),
  timeBlack :require("../assets/images/Time.png"),
  tickGrey :require("../assets/images/TickGrey.png"),
  tickWhite :require("../assets/images/TickWhite.png"),
  radioBlue:require("../assets/images/radioBlue.png"),
  radioGrey:require("../assets/images/radioGrey.png"),
  videoWhite:require("../assets/images/videoIcon.png"),
  videoBlack:require("../assets/images/videoBlack.png"),
  notesBlack:require("../assets/images/notesIconBlack.png"),
  notesWhite:require("../assets/images/notesWhite.png"),
  fileWhite:require("../assets/images/fileWhite.png"),
  fileBlack:require("../assets/images/fileBlack.png"),
  tickSuccess:require("../assets/images/successTick.png"),
  editPen:require("../assets/images/EditPen.png"),
  cartBlue :require("../assets/images/cartBlue.png"),
  btnBig:require("../assets/images/btnBackBig.png"),
  subsCardBlue:require("../assets/images/subsCard.png"),
  wallteWhite:require("../assets/images/walletWhite.png"),
  lineImage:require("../assets/images/lineImage.png"),
  cartWhite:require("../assets/images/cartWhite.png"),
  progressGrey:require("../assets/images/progressGrey.png"),
  cartIll:require("../assets/images/Illustration.png"),
  whiteLock:require("../assets/images/lockWhite.png"),
  clockWhite:require("../assets/images/clock.png"),
  offerOne:require("../assets/images/sampleSide.png"),
  whiteLine:require("../assets/images/singleLine.png"),
  verticalLine:require("../assets/images/verticalLine.png"),
  clockCart:require("../assets/images/clockCart.png"),
  calenderCart:require("../assets/images/calenderPic.png"),
  homeLogo:require("../assets/images/LogoHome.png"),
  redCross:require("../assets/images/redCross.png"),
  greenCross:require("../assets/images/greenCross.png"),
  calBlue:require("../assets/images/calBlue.png"),
  notesGrey:require("../assets/images/notesGrey.png"),
  clockBlueGrey:require("../assets/images/lightBlueClock.png"),
  vectorPeople:require("../assets/images/vectorPeople.png"),
  shareWhite:require("../assets/images/ShareWhite.png"),
  redTrash:require("../assets/images/redTrash.png"),
  downArrow:require("../assets/images/downArrow.png"),
  earning:require("../assets/images/earning.png"),
  book:require("../assets/images/book.png"),
  bookColl:require("../assets/images/bookColl.png"),
  students:require("../assets/images/students.png"),
  catEmpty:require("../assets/images/catEmpty.png"),
  courseEmpty:require("../assets/images/courseEmpty.png"),
  messageEmpty:require("../assets/images/messageEmpty.png"),
  notificationEmpty:require("../assets/images/notificationEmpty.png"),
  OffersEmpty:require("../assets/images/OffersEmpty.png"),
  subsEmpty:require("../assets/images/subsEmpty.png"),
  wishEmpty:require("../assets/images/wishEmpty.png"),
  noReview:require("../assets/images/noReview.png"),
  noChapter:require("../assets/images/noChapterFound.png"),
  noGroup:require("../assets/images/noGroup.png"),
  blueClock:require("../assets/images/BlueClock.png"),
  thickBook:require("../assets/images/thickBook.png"),
  radioBuy:require("../assets/images/radioBuy.png"),
  calendarIcon:require("../assets/images/calendarIcon.png"),
  SAMPLEIMAGE:require("../assets/images/Chemistry.png"),
  messageIcon:require("../assets/images/messageIcon.png"),
  congratsIcon:require("../assets/images/congratsIcon.png"),
  imageUrl:'https://images.unsplash.com/photo-1705591629142-9ba989fbc684?q=80&w=2787&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D'
};
