
export default {
  Onboarding: 'Onboarding',
  SignUp: 'SignUp',
  Home: 'Home',
  Wishlist: 'Wishlist',
  Calendar: 'Calendar',
  Courses: 'Courses',
  Settings: 'Settings',
  HomeTab: 'HomeTab',
  PurchasedCourse: 'PurchasedCourse',
  SelectUserType: 'SelectUserType',
  Profile: 'Profile',
  OtpVerify: 'OtpVerify',
  CategoryList: 'CategoryList',
  PurchasedCourseDetail: 'PurchasedCourseDetail',
  Cart: 'Cart',
  ChangePassword: 'ChangePassword',
  PaymentStructure: 'PaymentStructure',
  SingleCourseDetail: 'SingleCourseDetail',
  SampleVideoScreen: 'SampleVideoScreen',
  SignIn: 'SignIn',
  Filter: 'Filter',
  FilterInstructor:"FilterInstructor",
  BuyCourse: 'BuyCourse',
  AboutUs: 'AboutUs',
  AddReview: 'AddReview',
  Payments: 'Payments',
  PaymentsDetail: 'PaymentsDetail',
  EditProfile: 'EditProfile',
  Terms: 'Terms',
  Privacy: 'Privacy',
  MyAssignmets: 'My Assignmets',
  DeleteAccount: 'Delete Account',
  AddCourse: 'AddCourse',
  AddChapter: 'AddChapter',
  Notifications: 'Notifications',
  StudentList: 'Students',
  MyPlan: 'MyPlan',
  Voucher: 'MyPlan',
  WebView: 'WebView',
  MyCourses: 'My Courses',
  
  Reviews:"Reviews",

  InstructorCourses: 'InstructorCourses',
  InstructorList: 'InstructorList',
  InstructorDetail: 'InstructorDetail',

  MySubscriptions:"MySubscriptions",
  MySubscriptionsDetail:"MySubscriptionsDetail",

  ViewDetails: 'ViewDetails',
  ForgotPassword: 'ForgotPassword',
  ResetPassword: 'ResetPassword',
  CourseCategory: 'CourseCategory',
  SampleVimeo: 'SampleVimeo',
  AddNotes: 'AddNotes',
  NewHls: 'NewHls',
  Calendar: 'Calendar',
  SampleHsl: 'SampleHsl',
  SegmentationChapter: 'SegmentationChapter',

  // to be deleted
  SampleUpload: 'SampleUpload',
  //to be deleted
  SampleVideoUpload: 'SampleVideoUpload',

  AvailableOffers: 'AvailableOffers',
  AvailableCoupons: 'AvailableCoupons',
  GroupCoupons: 'GroupCoupons',
  GroupCouponsDetail: 'GroupCouponsDetail',
  CourseDiscount: 'CourseDiscount',
  CourseDiscountDetail: 'CourseDiscountDetail',
  SpecialOffers: 'SpecialOffers',
  JoinGroup:"JoinGroup",

  GroupCouponsCustom:"GroupCouponsCustom",

  MyVouchers:"MyVouchers",
  Upgrade:"UpgradeCourses",
  NewUpgrade:"NewUpgradeCourses",
  Downgrade:"Downgrade",
  CancelUpgrade:"CancelUpgrade",

  // to be definetly deleted
  NewGallerySample: 'NewGallerySample',
};
