export default {
  KumbhSans_Bold: 'KumbhSans-Bold',
  KumbhSans_ExtraBold: 'KumbhSans-ExtraBold',
  KumbhSans_Medium: 'KumbhSans-Medium',
  KumbhSans_Regular: 'KumbhSans-Regular',
  KumbhSans_SemiBold: 'KumbhSans-SemiBold',
  Urbanist_Bold: 'Urbanist-Bold',
  Urbanist_SemiBold: 'Urbanist-SemiBold',
  Urbanist_Medium: 'Urbanist-Medium',
  Urbanist_ExtraBold: 'Urbanist-ExtraBold',
  Urbanist_Thin: 'Urbanist-Thin',
  Montserrat_Bold: 'Montserrat-Bold',
  Montserrat_ExtraBold: 'Montserrat-ExtraBold',
  Montserrat_Medium: 'Montserrat-Medium',
  Montserrat_Regular: 'Montserrat-Regular',
  Montserrat_SemiBold: 'Montserrat-SemiBold',
  Montserrat_Thin: 'Montserrat-Thin',
  Poppins_Bold: 'Poppins-Bold',
  Poppins_SemiBold: 'Poppins-SemiBold',
  Poppins_Medium: 'Poppins-Medium',
  Poppins_Regular: 'Poppins-Regular',
  Poppins_Light: 'Poppins-Light',
  Poppins_ExtraLight: 'Poppins-ExtraLight',
  Poppins_Thin: 'Poppins-Thin',
  Merriweather_BoldItalic: 'Merriweather-BoldItalic',
};
