export const endpoints = {
  CHECK_TOKEN : 'student/check-user-device-token',
  CHECK_CART_STATUS : 'student/check-cart-tab',
  LOGIN: 'login',
  LOGIN_INS: 'instructor/login',
  GET_UNI: 'universities',
  SHOW_PROFILE: 'student/profile',
IS_EXPIRED: 'student/check-semester-status',
  SHOW_REPORT:"instructor/analytic-report",
  FULL_PROFILE:"profile",
  SHOW_INS_PROFILE: 'instructor/profile',
  UPDATE_PROFILE:"student/update-profile",
  UPDATE_INS_PROFILE:"instructor/update-profile",
  LOGOUT: 'logout',
  UNIVERSITIES: 'universities',
  SCHOOL_TYPE: 'student-options?type=school_type',
  SCHOOL_GRADE: 'departments?type=2',
  UNIVERSITIES_DEPRATMENT: 'departments',
  TRAINING_FIELD: 'training-fields',
  VERIFY_OTP: 'verify-otp', 
  SEND_OTP: 'send-otp',
  DELETE_ACCOUNT :"deactivate-account",
  STUDENT_REGISTER: 'student/register',
  COURSES_INSTURCTOR: 'courses?instructor_id=',
  COURSES: 'courses',
  COURSES_LIST: 'courses-list',
  COURSES_DETAIL: 'courses',
  COUPONS_DELETE: 'student/coupons',
  COURSES_CHAPTER: 'chapters',
  ADD_CHAPTER_VIDEOS :'add-chapter-videos',
  UPDATE_CHAPTER_VIDEOS :'update-chapter-videos',
  COUPONS:"get-coupons",
  COUPONS_DETAIL:"coupon-details",
  INSTRUCTOR:"instructors",
  STUDENT_WISHLIST:"student/wishlist",
  CATEGORIES:'categories',
  PAYMENTS:'payment',
  UPLOADVIDEO:'upload-video',
  UPLOADFILE:'upload-file',
  INSTRUCTOR_COURSES:'instructor/courses',
  INSTRUCTOR_PROFILE:'instructor/profile',
  CHAPTERS:'chapters',
  GET_NOTES:'/notes',
  NOTES:"instructor/add-notes",
  CHANGE_PASSWORD:"change-password",
  RESET_PASSWORD:'reset-password',
  FORGOT_PASSWORD:'forgot-password',
  ADD_TO_CART:'student/add-to-cart',
  REMOVE_FROM_CART:'student/remove-from-cart',
  GET_CART:'student/cart',
  PURCHASED_COURSES:"purchased-courses",
  PURCHASED_COURSES_DETAIL:"purchased-course-details",
  ORDERS:'student/orders',
  STUDENT_COUPONS:'student/coupons',
  ADD_GROUP:"add-group-coupon-member",
  GET_GROUP_COUPONS:"get-group-coupons",
  UPDATE_NOTES:"update-notes",
  DELETE_NOTES:"delete-notes",
  DELETE_GROUP_COUPONS_MEMBER:'delete-group-coupon-member',
  DELETE_VIDEOS:'videos',
  AVAILABLE_COUPONS :'get-coupons',
  APPLY_COUPON:"student/apply-coupon",
  REMOVE_COUPON:'student/remove-coupon',
  SEGEMENT_COUPON:"/student/segment",
  INSTALLMENT:"get-installment",
  CHECK_GROUP_DISCOUNT:"check-coupon-discount",
  REFUND_WALLET:"refund-to-wallet",
  CREATE_INSTALLMENT:"create-installment",
  APPLY_GROUP_COUPON:'add-group-coupon-member',
  GET_VOUCHER :"get-voucher",
  REVIEWS:"reviews",
  INSTRUCTORS_REVIEWS:"instructor/reviews",
  MARKASCOMPLETE:"mark-complete-watch-status",
  CANSEE:"change-view-status",
  ADS_ONS:'ads-ons',
  CART_UPGRADE:'student/add-adson-cart',
  CART_ADSON_UPGRADE:'student/add-adson',
  PUBLISH_REVIEW:"instructor/publish-review",
  ENROLLED_STUDENTS:"/instructor/enrolled-students",
  GET_PACKAGE:"student/get-package",
  BANNERS:"banners",
  WALLET:'wallet',
  GET_STORY:"student/story",
  CHARGE_COURSE_TYPE:"student/change-course-type",
  BUNNY_KEY:"get-bunny-key",
  GET_INSTALLMENT_PREVIEW:'get-installment-preview'
 
};
